metadata:
  annotations:
    configmap.fabric8.io/update-on-change: "fabric8-runtime-console"
    fabric8.io/iconUrl: "https://cdn.jsdelivr.net/gh/fabric8io/fabric8-console@f619a352/img/fabric8_icon.svg"
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: "OAUTH_ISSUER"
          valueFrom:
            configMapKeyRef:
              key: "oauth-issuer"
              name: "fabric8-runtime-console"
        - name: "OAUTH_LOGOUT_URI"
          valueFrom:
            configMapKeyRef:
              key: "oauth-logout-uri"
              name: "fabric8-runtime-console"
        - name: "OAUTH_CLIENT_ID"
          valueFrom:
            configMapKeyRef:
              key: "oauth-client-id"
              name: "fabric8-runtime-console"
        - name: "OAUTH_SCOPE"
          valueFrom:
            configMapKeyRef:
              key: "oauth-scope"
              name: "fabric8-runtime-console"
        - name: "OAUTH_AUTHORIZE_URI"
          valueFrom:
            configMapKeyRef:
              key: "oauth-authorize-uri"
              name: "fabric8-runtime-console"
        - name: "K8S_API_SERVER"
          valueFrom:
            configMapKeyRef:
              key: "api-server"
              name: "fabric8-runtime-console"
        image: "fabric8/fabric8-runtime-console:${project.version}"
        imagePullPolicy: "IfNotPresent"
        name: fabric8-runtime-console
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 120
          timeoutSeconds: 10
        ports:
        - containerPort: 8001
          name: "http"
      serviceAccountName: "fabric8-runtime-console"